In [1]:
import numpy as np
import pandas as pd

In [14]:
AE = 'autoencoder'
DCGAN = 'dcgan'
SRNN = 'sketchrnn'
SFRM = 'sketchformer'

In [15]:
df = pd.read_csv ('../data/sketch-order.csv')

In [16]:
df = df.fillna("")

In [17]:
top1_score = np.zeros(4)
top3_score = np.zeros(4)
top5_score = np.zeros(4)
top10_score = np.zeros(4)
category = "arm_order"
#category = "rabbit_order"
#category = "tree_order"

for k in range(len(df[category])):
    category_text = df[category][k].split('\r\n')
    if(len(category_text) > 1):
        if AE in category_text[0]:
            top1_score[0] +=1
        if DCGAN in category_text[0]:
            top1_score[1] +=1
        if SRNN in category_text[0]:
            top1_score[2] +=1
        if SFRM in category_text[0]:
            top1_score[3] +=1

        for i in range(3):
            if AE in category_text[i]:
                top3_score[0] +=1
            if DCGAN in category_text[i]:
                top3_score[1] +=1
            if SRNN in category_text[i]:
                top3_score[2] +=1
            if SFRM in category_text[i]:
                top3_score[3] +=1

        for i in range(5):
            if AE in category_text[i]:
                top5_score[0] +=1
            if DCGAN in category_text[i]:
                top5_score[1] +=1
            if SRNN in category_text[i]:
                top5_score[2] +=1
            if SFRM in category_text[i]:
                top5_score[3] +=1

        for i in range(10):
            if AE in category_text[i]:
                top10_score[0] +=1
            if DCGAN in category_text[i]:
                top10_score[1] +=1
            if SRNN in category_text[i]:
                top10_score[2] +=1
            if SFRM in category_text[i]:
                top10_score[3] +=1

In [18]:
print(top1_score / np.sum(top1_score))
print(top3_score / np.sum(top3_score))
print(top5_score / np.sum(top5_score))
print(top10_score / np.sum(top10_score))

[0.57142857 0.0952381  0.28571429 0.04761905]
[0.55555556 0.17460317 0.23809524 0.03174603]
[0.48571429 0.22857143 0.25714286 0.02857143]
[0.37619048 0.27142857 0.23333333 0.11904762]
